clc;
clear all;
close all;
n=input('Enter the value for time ');
a=input('Enter the value for Amplitude ');
t=-n:1:n;
y=a*(t.*t);
stem(t,y);
ylabel('Amplitude');
xlabel('Time');
title('Parabolic Signal');